const types = {
  RECEIVE_LOGIN_SUCCESS: "RECEIVE_LOGIN_SUCCESS",
  RECEIVE_LOGIN_FAILURE: "RECEIVE_LOGIN_FAILURE",
  RECEIVE_LOGOUT_SUCCESS: "RECEIVE_LOGOUT_SUCCESS",
  UI_WAITING_BEGIN: "UI_WAITING_BEGIN",
  UI_WAITING_FINISH: "UI_WAITING_FINISH"
};

export default types;
